apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glusterfs-grafana-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G
  storageClassName: ""
  volumeName: gv0-glusterfs-pv