apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glusterfs-test-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
  storageClassName: ""
  volumeName: gv0-glusterfs-pv