apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: magpie-storage-class
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: magpie-nfs-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/pixiu/k8
    server: magpie.rack-1.gaolab
  persistentVolumeReclaimPolicy: Retain
  storageClassName: magpie-storage-class
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: magpie-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: magpie-storage-class
