apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pachyderm-loki-storage-class
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: magpie-nfs-pv-pachyderm-loki
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/pixiu/k8/pachyderm/loki
    server: magpie.rack-1.gaolab
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pachyderm-loki-storage-class
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pachyderm-postgres-storage-class
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: magpie-nfs-pv-pachyderm-postgres
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/pixiu/k8/pachyderm/postgres
    server: magpie.rack-1.gaolab
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pachyderm-postgres-storage-class
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pachyderm-etcd-storage-class
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: magpie-nfs-pv-etcd-postgres
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/pixiu/k8/pachyderm/etcd
    server: magpie.rack-1.gaolab
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pachyderm-etcd-storage-class
---