apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: magpie-storage-class
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: magpie-etcd-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/pixiu/k8/pachyderm/etcd
    server: magpie.rack-1.gaolab
  persistentVolumeReclaimPolicy: Retain
  storageClassName: magpie-storage-class
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: magpie-etcd-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: magpie-storage-class
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: magpie-loki-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/pixiu/k8/pachyderm/loki
    server: magpie.rack-1.gaolab
  persistentVolumeReclaimPolicy: Retain
  storageClassName: magpie-storage-class
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: magpie-loki-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: magpie-storage-class
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: magpie-postgres-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/pixiu/k8/pachyderm/postgres
    server: magpie.rack-1.gaolab
  persistentVolumeReclaimPolicy: Retain
  storageClassName: magpie-storage-class
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: magpie-postgres-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: magpie-storage-class
