apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcp-pmlogger-pmproxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pcp-pmlogger-pmproxy
  template:
    metadata:
      labels:
        app: pcp-pmlogger-pmproxy
    spec:
      containers:
      - name: pcp-pmlogger-pmproxy
        image: chrisagrams/pcp-pmlogger-pmproxy:lmsensors
        args: ["192.168.203.0/24"]
---
apiVersion: v1
kind: Service
metadata:
  name: pcp-pmlogger-pmproxy
spec:
  selector:
    app: pcp-pmlogger-pmproxy
  ports:
  - port: 44322
    targetPort: 44322
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcp-redis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pcp-redis
  template:
    metadata:
      labels:
        app: pcp-redis
    spec:
      containers:
      - name: pcp-redis
        image: redis
---
apiVersion: v1
kind: Service
metadata:
  name: pcp-redis
spec:
  selector:
    app: pcp-redis
  ports:
  - port: 6379
    targetPort: 6379
